### ISSUE TITLE
SIMD immintrin.h inconsistencies with __m256d type

### ISSUE THREAD

**Issue by cdelguercio** [ignotuscaligo/ray-tracer#7]
On linux __m256d doesn't have a member named "m256d_f64", and I believe the type is simplified to just an array. I haven't dug any deeper than that. Here's my fix on linux:

cpp/Vector.cpp
```
double Vector::dot(const __m256d& a, const __m256d& b) noexcept
{
    const __m256d mul = _mm256_mul_pd(a, b);

    return mul.m256d_f64[0] + mul.m256d_f64[1] + mul.m256d_f64[2];
}
```

changed to:
```
double Vector::dot(const __m256d& a, const __m256d& b) noexcept
{
    const __m256d mul = _mm256_mul_pd(a, b);

    return mul[0] + mul[1] + mul[2];
}
```

Please advise on the cleanest way to separate the two approaches with compiler directives

**Comment by ignotuscaligo** [comment]
Resolved by #8
